name: "Testing Flatpak External Data Checker"
author: "The Flatpak External Data Checker authors"
description: "A tool for checking if the external data used in Flatpak manifests is still up to date" 
inputs:
  # todo these are untrusted inputs, so ensure we handle safely
  config_file:
    description: "Set the name for a JSON config file that can store configuration options passed to the action. Note the file name is always appended with .json"
    required: false
    default: "flathub.json"
  github_org_wide:
    description: "Enter an exact GitHub organization name to enable this action for GitHub organization wide mode. This is not needed if only updating a single repo."
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/vchernin/flatpak-external-data-checker:latest"
  # todo docs seem to specify this, but maybe env can be used instead
  args:
    - ${{ inputs.config_file }}
    - ${{ inputs.github_org_wide }}
  env: 
    # todo do we need both author and commiter names here? script isn't using them
    GIT_AUTHOR_NAME: Flatpak External Data Checker
    GIT_COMMITTER_NAME: Flatpak External Data Checker
    GIT_AUTHOR_EMAIL: "'${{ github.actor }}'@users.noreply.github.com"
    GIT_COMMITTER_EMAIL: "'${{ github.actor }}'@users.noreply.github.com"
    EMAIL: "'${{ github.actor }}'@users.noreply.github.com"
    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    # CONFIG_FILE: ${{ inputs.config_file }}
    # GITHUB_ORG_WIDE: ${{ inputs.github_org_wide }}
    GITHUB_WORKSPACE: '${{ github.workspace }}' # todo verify
  entrypoint: "entrypoint.sh"
